name: IONOS.space

on: [push]

jobs:
  ionos-space:
    runs-on: ubuntu-latest
    steps:
      - name: Get Ionos Project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          project: d177dd4a-34a4-4936-a27a-810d2cd18b68
          service-host: api-us.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Node.js 12.16.x
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - name: Prepare Project build environment
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: npm install
      - name: Build Node project
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: npm run start
        env:
          SITE_URL: ${{ steps.project.outputs.site-url }}
          CI: true
      - name: Deploy to IONOS
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          service-host: api-us.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
          remote-host: ${{ steps.project.outputs.remote-host }}
          dist-folder: dist
          project: d177dd4a-34a4-4936-a27a-810d2cd18b68
          storage-quota: ${{ steps.project.outputs.storage-quota }}
          branch-id: ${{ steps.project.outputs.branch-id }}
